# mysql
spring:
  datasource:
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:pickup_db}
    url: jdbc:mysql://database-1.cp2q4u86kgsu.ap-northeast-2.rds.amazonaws.com:3306/pickup_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:admin}
    password: ${MYSQL_PASSWORD:pickup1234}
  # redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  # Swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# jwt
jwt:
  secretkey: ${JWT_SECRET_KEY:1q2w3e4r5t6y7u8i9o0p1q2w3e4r5t6y7u8i9o0p!}

# log
logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    core.pickupbackend: ${LOG_LEVEL_APP:DEBUG}

# fcm
fcm:
  json:
    link: ${FCM_JSON_PATH:classpath:fcm/firebase-adminsdk.json}

# Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
  api-docs:
    path: /v1/api-docs

# cors
cors:
  allowed-origins: http://13.125.58.70:8080/