# mysql
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  # redis
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      password: ${SPRING_DATA_REDIS_PASSWORD:}

  # Swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# jwt
jwt:
  secretkey: 1q2w3e4r5t6y7u8i9o0p1q2w3e4r5t6y7u8i9o0p!

# log
logging:
  level:
    root: INFO
    core.pickupbackend: DEBUG

# fcm
fcm:
  json:
    link: classpath:fcm/firebase-adminsdk.json

# Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
  api-docs:
    path: /v1/api-docs