# mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pickup_db # create sql 그대로 작성하면 동일하게 유지
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root # root 계정
    password: ${MYSQL_ROOT_PASSWORD:rkdglqkr12@} # root 계정 비밀번호 입력

  # redis
  # 설치 기본값 그대로 사용
  data:
    redis:
      host: localhost
      port: 6379
      password: ${SPRING_DATA_REDIS_PASSWORD:}

  # Swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# jwt
# 환경변수에 key 입력
jwt:
  secretkey: 1q2w3e4r5t6y7u8i9o0p1q2w3e4r5t6y7u8i9o0p!

# log
logging:
  level:
    root: warn
    core.pickupbackend: debug
    org.springframework.jdbc.core: TRACE

log:
  path: src/main/resources/log
  filename: application
  pattern: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# fcm
# 환경변수에 link 입력 /resources/fcm/~
fcm:
  json:
    link: classpath:fcm/firebase-adminsdk.json

# Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
  api-docs:
    path: /v1/api-docs

# cors
cors:
  allowed-origins: http://localhost:8080
